services:
    inscricao.repository:
        class:  Infrastructure\Persistence\Doctrine\InscricaoRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Model\Inscricao\Inscricao

    oportunidade.repository:
        class:  Infrastructure\Persistence\Doctrine\OportunidadeRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Model\Oportunidade\Oportunidade
