app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_inscricao:
    resource: "@AppBundle/Controller/InscricaoController.php"
    type: rest

app_oportunidade:
    resource: "@AppBundle/Controller/OportunidadeController.php"
    type: rest
