jms_serializer:
    handlers:
        datetime:
            default_format: 'd/m/Y'
            default_timezone: 'UTC'
    metadata:
        auto_detection: true
        directories:
            DomainModel:
                namespace_prefix: Domain\Model
                path: '%kernel.root_dir%/Resources/infrastructure/serializer/jms'
            DataTransferObject:
                namespace_prefix: Presentation\DataTransferObject
                path: '%kernel.root_dir%/Resources/infrastructure/serializer/jms/dto'

services:

    relation_handler:
        class: Infrastructure\Serializer\RelationsHandler
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
             - {name: "jms_serializer.handler", type : Domain\Model\Oportunidade\Oportunidade, direction: "deserialization", format: "json", method: "serializeRelations"}
             - {name: "jms_serializer.handler", type : Domain\Model\Inscricao\Inscricao, direction: "deserialization", format: "json", method: "serializeRelations"}
