services:
    app.event-dispatcher.service:
        class: AppBundle\Service\EventDispatcherService
        arguments: ['@event_dispatcher']

    app.inscricao.service:
        class: AppBundle\Service\InscricaoService
        arguments: ['@app.event-dispatcher.service', '@inscricao.repository', '@infra.storage.service']

    app.oportunidade.service:
        class: AppBundle\Service\OportunidadeService
        arguments: ['@oportunidade.repository']